title: Gate to Freedom
description: 公开透明的群公告与治理信息归档（占位文案）
url: https://gate2freedom.com
baseurl: ""               # 顶级域直挂；如挂子目录再改
lang: zh-CN
timezone: Asia/Shanghai

# 文章链接格式
permalink: /:categories/:year/:month/:day/:title/

# 插件
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

# 公告分页
paginate: 12
paginate_path: "/announcements/page:num/"

# 让所有 _posts 默认用 post 布局
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post

# 导航（用于头部导航渲染）
nav:
  - name: 公告
    url: /announcements/
  - name: 群规
    url: /rules/
  - name: 关于
    url: /about/

# Feed（可选）
feed:
  path: feed.xml
