title: Gate to Freedom
description: 公开透明的群公告与治理信息归档（占位文案）
url: https://gate2freedom.com
baseurl: ""                 # 自定义域名直挂顶级域；若挂子路径，改这里
lang: zh-CN
timezone: Asia/Shanghai

# 文章与页面
permalink: /:categories/:year/:month/:day/:title/
collections:
  posts:
    output: true

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

# 公告分页：每页 12 篇，可自行调
paginate: 12
paginate_path: "/announcements/page:num/"

# 让所有 _posts 默认用 post 布局（修复“空白+小字”）
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post

# 导航（在 header.html 中使用）
nav:
  - name: 公告
    url: /announcements/
  - name: 群规
    url: /rules/
  - name: 关于
    url: /about/

# Feed 设置（可选）
feed:
  path: feed.xml
