title: Gate to Freedom
description: 公开透明的群公告与治理信息归档（占位文案）
url: https://gate2freedom.com
baseurl: ""
lang: zh-CN
timezone: Asia/Shanghai

permalink: /:categories/:year/:month/:day/:title/

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2     # ← v2 分页插件

# 所有 _posts 默认使用 post 布局
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post

# 顶部导航（header 用）
nav:
  - name: 公告
    url: /announcements/
  - name: 群规
    url: /rules/
  - name: 关于
    url: /about/

feed:
  path: feed.xml
